os:
  - linux
  - osx

language: node_js
dist: bionic

env:
  - TEST_COMMAND=coverage
  - TEST_COMMAND=e2e

addons:
  firefox: latest

services:
  - xvfb

branches:
  only:
    - master
    - /^rc-.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

before_install:
  - npm i -g @skyux-sdk/cli
  - skyux certs install

script: "npm run lint && npm run $TEST_COMMAND"

after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage/builder -F builder
  - bash <(curl -s https://codecov.io/bash) -s coverage/runtime/ -F runtime
  - bash <(curl -s https://codecov.io/bash) -s coverage/src-app/ -F srcapp

# Run the deployment after all jobs have been successfully completed.
# https://docs.travis-ci.com/user/build-stages
jobs:
  include:
    - stage: deploy
      env: TEST_COMMAND=none
      script: bash <(curl -s https://blackbaud.github.io/skyux-travis/after-success.sh)
